### ISSUE TITLE
CPS 0.1.0 checklist

### ISSUE THREAD

**Issue by alaviss** [disruptek/cps#187]
Just things that are on top of my head that we should get done before 0.1.0, feel free to edit.

- [x] Have control-flow functions as expected
  - [x] Exception unwinding across continuations
- [ ] Parentage across continuation bases (should be possible as a side effect of fixing #188)
- [x] Document how to debug CPS and/or submit a bug report
- [ ] Good traces
- [ ] (Maybe) Document currently unsupported CPS rewrites by emitting more error nodes
  - [x] Generics (this one should be done early since people will try this out)
  - [x] `var`/`openArray`/`lent` parameters
  - [ ] Lambda/closures within `proc`
  - [ ] Nested procs
  - [ ] CPS proc types

**Comment by disruptek** [comment]
Added a couple. :+1:

**Comment by zevv** [comment]
For me, #1 is a working return value shim for procs from imports.

**Comment by disruptek** [comment]
This was broken up into separate issues and 0.1.0 is long gone.
